senders:
  - name: heartbeat
    tele: tele-heartbeat
    folder: /home/ledmirage/Downloads/wspace/telego/hb

teleconfigs:
  - name: tele-heartbeat
    token: 123456789:ABCdefg-aaaaaaaaaaaaaaa_bbbbbbbbbbbb
    chatid: -123456789
